_BASE_: "Base.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 32
  BASE_LR: 0.02
  STEPS: (17400, 23200)
  MAX_ITER: 29000
  WARMUP_ITERS: 906
TEST:
  EVAL_PERIOD: 7250
VIS_PERIOD: 580
DATASETS:
  TRAIN: ('ARKitScenes_train', 'ARKitScenes_val')
  TEST: ('ARKitScenes_test',) 
  CATEGORY_NAMES: ('bed', 'table', 'chair', 'fireplace', 'machine', 'cabinet', 'oven', 'shelves', 'sink', 'stove', 'bathtub', 'toilet', 'sofa', 'television', 'refrigerator')
  FOLDER_NAME: 'Omni3D_pl'
MODEL:
  META_ARCHITECTURE: RCNN3D_text
  ROI_HEADS:
    NAME : ROIHeads3D_Text
    NUM_CLASSES: 15
  STABILIZE: 0.5

