_BASE_: "Base.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 32
  BASE_LR: 0.02
  STEPS: (17400, 23200)
  MAX_ITER: 29000
  WARMUP_ITERS: 906
TEST:
  EVAL_PERIOD: 7250
VIS_PERIOD: 580
DATASETS:
  TRAIN: ('SUNRGBD_train', 'SUNRGBD_val')
  TEST: ('SUNRGBD_test',) 
  CATEGORY_NAMES: ('bicycle', 'books', 'bottle', 'chair', 'cup', 'laptop', 'shoes', 'towel', 'blinds', 'window', 'lamp', 'shelves', 'mirror', 'sink', 'cabinet', 'bathtub', 'door', 'toilet', 'desk', 'box', 'bookcase', 'picture', 'table', 'counter', 'bed', 'night stand', 'pillow', 'sofa', 'television', 'floor mat', 'curtain', 'clothes', 'stationery', 'refrigerator', 'bin', 'stove', 'oven', 'machine')
  FOLDER_NAME: 'Omni3D_pl'
MODEL:
  META_ARCHITECTURE: RCNN3D_text
  ROI_HEADS:
    NAME : ROIHeads3D_Text
    NUM_CLASSES: 38
  STABILIZE: 0.5