_BASE_: "Base.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 32
  BASE_LR: 0.01
  STEPS: (17400, 23200)
  MAX_ITER: 29000
  WARMUP_ITERS: 906
TEST:
  EVAL_PERIOD: 7250
VIS_PERIOD: 580
DATASETS:
  TRAIN: ('nuScenes_train', 'nuScenes_val')
  TEST: ('nuScenes_test',) 
  CATEGORY_NAMES: ('pedestrian', 'car', 'truck', 'traffic cone', 'barrier', 'motorcycle', 'bicycle', 'bus', 'trailer')
  FOLDER_NAME: 'Omni3D_pl'
MODEL:
  META_ARCHITECTURE: RCNN3D_text
  ROI_HEADS:
    NAME : ROIHeads3D_Text
    NUM_CLASSES: 9
  STABILIZE: 0.5